online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('add_product', views.add_product, name='add_product'),
    path('cart', views.cart, name='cart'),
    path('remove_from_cart/<int:product_id>', views.remove_from_cart, name='remove_from_cart'),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('<int:product_id>', views.product_details, name='product_details'),
    path('post_review/<int:product_id>', views.post_review, name='post_review'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout, name='logout'),
    path('category/<category_name>', views.browse, name='browse'),
    path('', views.homepage, name='homepage')
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.exceptions import ValidationError


class Product(models.Model):
    name = models.CharField(max_length=150)
    quantity = models.PositiveIntegerField(default=0)
    price = models.FloatField()
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    primary_image = models.ForeignKey('ProductImage', on_delete=models.SET_NULL,
                                      related_name='+', null=True, blank=True)
    categories = models.ManyToManyField('Category')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_details', kwargs={'product_id':self.id})


def get_product_dir(image, filename):
    return f'{image.product.id}/{filename}'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_product_dir, null=True)


class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    parent = models.ForeignKey('Category', on_delete=models.SET_NULL,
                               related_name='children', null=True, blank=True)

    def __str__(self):
        return self.name


def validate_rating(rating):
    if not 1 <= rating <= 5:
        raise ValidationError('Invalid rating')


class Review(models.Model):
    rating_choices = [
        (1, '&#9734;'),
        (2, '&#9734;'),
        (3, '&#9734;'),
        (4, '&#9734;'),
        (5, '&#9734;')
    ]

    content = models.CharField(max_length=2000)
    rating = models.PositiveSmallIntegerField(validators=[validate_rating], choices=rating_choices, default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

shop/forms.py
from django import forms
from .models import Product, Review
from django.core.exceptions import ValidationError


class ProductForm(forms.ModelForm):
    images = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple':True}))
    i_primary_image = forms.IntegerField()

    class Meta:
        model = Product
        fields = ['name', 'quantity', 'price', 'categories']
        widgets = {'name': forms.Textarea(attrs={'cols':80, 'rows':1})}

    def clean_i_primary_image(self):
        i_primary_image = self.cleaned_data.get('i_primary_image')
        if i_primary_image < 0 or i_primary_image > len(self.files.getlist('images')) - 1:
            raise ValidationError('Invalid primary image index')
        return i_primary_image

    def clean(self):
        cleaned_data = super().clean()
        if len(self.files.getlist('images')) > 5:
            raise ValidationError('You can only upload up to 5 images')


class AddToCartForm(forms.Form):
    quantity = forms.IntegerField()


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'rating']
        widgets = {'content': forms.Textarea(attrs={'cols':150, 'rows':5}),
                   'rating': forms.RadioSelect()}


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

shop/views.py
from django.shortcuts import render
from .models import Product, ProductImage, Category
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ProductForm, AddToCartForm, LoginForm, ReviewForm
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.contrib import auth
from django.db.models import Avg
from .cart import Cart


def homepage(request):
    products = Product.objects.all()
    for product in products:
        mean_rating = product.review_set.all().aggregate(Avg('rating'))['rating__avg']
        if mean_rating:
            product.rating_stars = rating_stars(round(mean_rating))
        else:
            product.rating_stars = ''

    categories = Category.objects.filter(parent__isnull=True)
    template = loader.get_template('shop/browse.html')
    context = {'products': products, 'sibling_categories': categories}
    return HttpResponse(template.render(context, request))


def add_product(request):
    if request.method == 'GET':
        form = ProductForm(label_suffix='')
    elif request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, label_suffix='')
        if form.is_valid() and len(request.FILES.getlist('images')) <= 5:
            product = form.save(commit=False)
            product.seller = request.user
            product_images = []
            product.save()
            product.categories.add(*form.cleaned_data['categories'])
            for imagefile in request.FILES.getlist('images'):
                product_image = ProductImage(product=product, image=imagefile)
                product_images.append(product_image)
                product_image.save()
            product.primary_image = product_images[form.cleaned_data['i_primary_image']]
            product.save()
            return HttpResponseRedirect(reverse(homepage))
    template = loader.get_template('shop/add_product.html')
    context = {'form':form}
    return HttpResponse(template.render(context, request))


def product_details(request, product_id):
    product = Product.objects.get(id=product_id)
    add_to_cart_form = AddToCartForm()

    review_form = ReviewForm(label_suffix='')
    review_form['content'].label = 'Leave a Review'
    reviews = product.review_set.all()
    if reviews.filter(user=request.user).exists():
        for field in review_form.fields.values():
            field.disabled = True
        review_form_disabled = True
    else:
        review_form_disabled = False

    if len(reviews) > 0:
        mean_rating = reviews.aggregate(Avg('rating'))['rating__avg']
        stars_str = rating_stars(round(mean_rating))
    else:
        stars_str = ""
    recent_reviews = reviews.reverse()[:5]
    for review in recent_reviews:
        review.stars_str = rating_stars(review.rating)

    template = loader.get_template('shop/product_details.html')
    context = {
        'product': product,
        'rating_stars_str': stars_str,
        'add_to_cart_form': add_to_cart_form,
        'review_form': review_form,
        'review_form_disabled': review_form_disabled,
        'reviews': recent_reviews,
        }
    return HttpResponse(template.render(context, request))


def rating_stars(rating):
    total_stars = 5
    stars_str = "&#9733;"*rating
    stars_str += "&#9734;"*(total_stars-rating)
    return stars_str


@require_POST
def post_review(request, product_id):
    product = Product.objects.get(id=product_id)
    review_form = ReviewForm(request.POST, label_suffix='')
    if review_form.is_valid() and not product.review_set.filter(user=request.user).exists():
        review = review_form.save(commit=False)
        review.product = product
        review.user = request.user
        review.save()

    return HttpResponseRedirect(reverse('product_details', args=[product_id]))


@require_POST
def add_to_cart(request, product_id):
    cart = Cart(request)
    product = Product.objects.get(id=product_id)
    form = AddToCartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product_id, cd['quantity'])
    return HttpResponseRedirect(reverse(homepage))


@require_POST
def remove_from_cart(request, product_id):
    cart = Cart(request)
    cart.remove(product_id)
    return HttpResponseRedirect(reverse('cart'))


def cart(request):
    cart = Cart(request)
    template = loader.get_template('shop/cart.html')
    context = {'cart': cart, 'total_price': cart.total_price()}
    return HttpResponse(template.render(context, request))


def login_page(request):
    if request.method == 'GET':
        form = LoginForm()
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = auth.authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                auth.login(request, user)
                return HttpResponseRedirect(reverse(homepage))
            else:
                return HttpResponse('Invalid login')

    template = loader.get_template('shop/login.html')
    context = {'form': form}
    return HttpResponse(template.render(context, request))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse(homepage))


def browse(request, category_name):
    category = Category.objects.get(name=category_name)

    if category.parent:
        sibling_categories = category.parent.children
    else:
        sibling_categories = Category.objects.filter(parent__isnull=True)
    sibling_categories = sibling_categories.exclude(id=category.id)

    child_categories = category.children.all()

    products = category_products(category)
    for product in products:
        mean_rating = product.review_set.all().aggregate(Avg('rating'))['rating__avg']
        if mean_rating:
            product.rating_stars = rating_stars(round(mean_rating))
        else:
            product.rating_stars = ''

    template = loader.get_template('shop/browse.html')
    context = {
        'products': products,
        'current_category': category,
        'sibling_categories': sibling_categories,
        'child_categories': child_categories,
        'parent_category': category.parent
        }
    return HttpResponse(template.render(context, request))


def category_products(category):
    products = category.product_set.all()
    if products:
        return products
    else:
        child_categories = category.children.all()
        products = Product.objects.none()
        for child_category in child_categories:
            products = products.union(category_products(child_category))
        return products

shop/templates/shop/add_product.html
{% extends "shop/base.html" %}
{% load static %}

{% block head %}
  <title>Add Product</title>
  <link href="{% static 'shop/add_product.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {% for field in form %}
    {% if forloop.counter != 6 %}
      <p>
        {{ field.label_tag }}
        {{ field }}
      </p>
    {% else %}
      {{ field.as_hidden }}
    {% endif %}
  {% endfor %}
  <input type="submit" value="Submit">
</form>

<script src="{% static 'shop/auto_textarea.js' %}"></script>
<script src="{% static 'shop/primary_image_select.js' %}"></script>
{% endblock body %}

shop/templates/shop/base.html
{% load static %}

<html lang="en">
<head>
  <link href="{% static 'shop/base.css' %}" rel="stylesheet">
  {% block head %}
  {% endblock head %}
</head>
<body>
  <header>
      <a id="logo" href="{% url 'homepage' %}">Atlantic</a>
      <a id="cart" href="{% url 'cart' %}">Cart</a>
      {% if user.is_authenticated %}
        <a class="user_auth" href="{% url 'logout' %}">Log out</a>
        <a class="add_product" href="{% url 'add_product' %}">Add product</a>
      {% else %}
        <a class="user_auth" href="{% url 'login' %}">Log in</a>
      {% endif %}
  </header>
  {% block body %}
  {% endblock body %}
</body>
</html>

shop/templates/shop/browse.html
{% extends "shop/base.html" %}
{% load static %}

{% block head %}
  <title>Shop</title>
  <link href="{% static "shop/browse.css" %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<div class="main">
  <div class="categories">
    {% if parent_category %}
      <a href="{% url 'browse' parent_category.name %}">
        &#10094; {{ parent_category.name }}
      </a>
    {% endif %}
    <ul>
    {% if current_category %}
      <li>
        <a href="{% url 'browse' current_category.name %}">
          <strong>{{ current_category.name }}</strong>
        </a>

      {% if child_categories %}
        <ul class="child_categories">
          {% for category in child_categories %}
            <li>
              <a href="{% url 'browse' category.name %}">
                {{ category.name }}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
      </li>
    {% endif %}
    {% for category in sibling_categories %}
      <li>
        <a class="sibling_category" href="{% url 'browse' category.name %}">
          {{ category.name }}
        </a>
      </li>
    {% endfor %}
    </ul>
</div>
  <div class="products">
    {% for product in products %}
      <a href="{{ product.get_absolute_url }}">
        <div class="image">
          <img src="{% if product.primary_image %}{{ product.primary_image.image.url }}
                    {% else %}{% static 'shop/default_image.png' %}{% endif %}">
          <div>{{ product.name | truncatechars:50 }}</div>
          <div class="rating-stars">{{ product.rating_stars | safe }}</div>
          <div>&euro; {{ product.price | floatformat:"2" }}</div>
        </div>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock body %}

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}
{% load static %}

{% block head %}
  <title>Cart</title>
  <link href="{% static 'shop/cart.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<div class="main">
  <table class="cart">
    <thead>
      <tr>
        <th></th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for product in cart %}
        <tr>
          <td class="image">
            <img src="{% if product.product.primary_image %}
            {{product.product.primary_image.image.url}}
            {% else %}{% static 'shop/default_image.png' %}{% endif %}">
          </td>
          <td>{{ product.name }}</td>
          <td>{{ product.quantity }}</td>
          <td>{{ product.price | floatformat:"2" }}</td>
          <td>
            <form action="{% url 'remove_from_cart' product.product.id %}" method="post">
              <input type="submit" value="Remove">
              {% csrf_token %}
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="order">
    <div class="price">Total: &euro; {{ total_price | floatformat:"2" }}</div>
  </div>
</div>

{% endblock body %}

shop/templates/shop/login.html
{% extends "shop/base.html" %}
{% load static %}

{% block head %}
  <title>Login</title>
  <link href="{% static 'shop/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log in">
  </form>
{% endblock body %}

shop/templates/shop/product_details.html
{% extends 'shop/base.html' %}
{% load static %}

{% block head %}
  <title>{{ product.name }}</title>
  <link href="{% static "shop/product_details.css" %}" rel="stylesheet">
{% endblock head %}

{% block body %}
<div id="content">
<div id="main">
  <div class="image">
    <img src="{{ product.primary_image.image.url }}">
    {% for image in product.productimage_set.all %}
      {% if image != product.primary_image %}
        <img src="{{ image.image.url }}">
      {% endif %}
    {% endfor %}
    <button class="previous">&#10094;</button>
    <button class="next">&#10095;</button>
  </div>
  <div id="product-info">
    <div class="product-name">{{ product.name }}</div>
    <div class="rating-stars">{{ rating_stars_str | safe }}</div>
    <div class="product-price">&euro; {{ product.price | floatformat:"2" }}</div>
    <form action="{% url 'add_to_cart' product.id %}" class="add-to-cart" method="post">
      {% csrf_token %}
      {{ add_to_cart_form.as_p }}
      <input type="submit" value="Add to cart">
    </form>
  </div>
</div>
<div>
  <form action="{% url 'post_review' product.id %}" class="review-submit" method="post">
    {% csrf_token %}
    <p class="review-text">
      {{ review_form.content.label_tag }}
      {{ review_form.content }}
    </p>

    <div class="rating-select">
      {% for radio in review_form.rating %}
        <label for="{{ radio.id_for_label }}">{{ radio.choice_label | safe }}</label>
        {{ radio.tag }}
      {% endfor %}
    </div>

    <input type="submit" value="Submit Review" {% if review_form_disabled %}disabled{% endif %}>
  </form>
  <div class="reviews">
    {% for review in reviews %}
      <div class="rating-stars">{{ review.stars_str | safe }}</div>
      <p>{{ review.content }}</p>
    {% endfor %}
  </div>
</div>
</div>

<script src="{% static 'shop/image_slideshow.js' %}"></script>
<script src="{% static 'shop/rating_stars.js' %}"></script>
{% endblock body %}